# Generated by Django 4.2.21 on 2025-05-21 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clicked_as_prayed_over_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("has_been_changed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("praying", "Praying"),
                            ("accomplished", "Accomplished"),
                            (
                                "changed_or_no_longer_needed",
                                "Changed or No longer Needed",
                            ),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("ai_generation_references", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
